root: true
parser: '@typescript-eslint/parser'
extends: 
  - plugin:astro/recommended
overrides:
  -files:
    - "*.astro"
  parser: astro-eslint-parser
  parserOptions:
    parser: "@typesript-eslint/parser"
    extraFileExtensions:
      - ".astro"
